decoration {
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}

exec-once = elephant
exec-once=walker --gapplication-service
bind = SUPER, space, exec, walker
# exec-once = nwg-dock-hyprland -f -p left -x -c -- walker --modules applications

env = HYPRCURSOR_THEME,Adwaita
env = HYPRCURSOR_SIZE,32
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,32
